[profile.default]
solc = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
goerli = {key = "${ETHERSCAN_API_KEY}"}
mainnet = {key = "${ETHERSCAN_API_KEY}"}
